version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8876:80"
    container_name: app_test_nginx
    depends_on:
      - app

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: app_test_laravel
